name: CI

on:
  pull_request:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: macOS

    steps:
      - uses: actions/checkout@v5

      - name: Build
        run: swift build --product GhDashboard

      - name: Test
        run: swift run CoreTests
